LUDIC Game Library: Ludic::FontResource::createFontResource
createFontResource
FontResource
getFontPtr
getSizeResource
operator ALLEGRO_FONT *
FontResource * FontResource::createFontResource (const String & fileName, unsigned int fontSize) static
Parameters
fileName
fontSize
Returns
Definition at line 28 of file font_resource.cpp.
References Ludic::ResourceManager::addResource(), FontResource(), Ludic::ResourceManager::getResource(), and Ludic::ResourceManager::Instance().