LUDIC Game Library: Ludic::ImageResource::createImageResource
createImageResource
getSubImageResource
loadImageResource
operator ALLEGRO_BITMAP *
setColorKey
ImageResource * ImageResource::createImageResource (const String & label, int width, int height) static
Returns
Definition at line 26 of file image_resource.cpp.
References Ludic::ResourceManager::addResource(), Ludic::ResourceManager::getResource(), and Ludic::ResourceManager::Instance().