/**
 * @file AddOnException.h
 * @author Michell Stuttgart
 * @date 12/21/2013
 */
 
#pragma once

#include "Exception.h"

namespace sgl {

/**
 * @class AddOnException
 * @brief Base class responsible for catching exceptions generated by the AddOn
 * Allegro5.
 */
class AddOnException: public Exception {

public:

	/**
	 * @brief Method responsible for returning a description of the exception.
	 * @return String containing the description of the exception.
	 */
	virtual const char* what() const throw();

};

} /* namespace sgl */
