/**
 * @file AddOnException.h
 * @author Michell Stuttgart
 * @date 12/21/2013
 */
#ifndef ADDONEXCEPTION_H_
#define ADDONEXCEPTION_H_

#include "Exception.h"

namespace sgl {
	namespace core {

/**
 * @class AddOnException
 * @brief Base class responsible for catching exceptions generated by the AddOn
 * Allegro5.
 */
class AddOnException: public Exception {

public:

	/**
	 * @brief Method responsible for returning a description of the exception.
	 * @return String containing the description of the exception.
	 */
	virtual const char* what() const throw();

};

} /* namespace core */
} /* namespace sgl */

#endif /* ADDONEXCEPTION_H_ */
