/**
 * @file Exception.h
 * @author Michell Stuttgart
 * @date 17/12/2013
 */

#pragma once

#include <exception>

namespace sgl {

/**
 * @class Exception
 * @brief Base class responsible for catching exceptions generated by fail in the SGL.
 *
 * Can be used as a basis for other classes that deal with more specific exceptions.
 *
 */
class Exception: public std::exception {

	public:

	/**
	 * @brief Method responsible for returning a description of the exception.
	 * @return String containing the description of the exception.
	 */
	virtual const char* what() const throw();

};

} /* namespace sgl */
