/**
 * @file FileException.h
 * @date 17/12/2013
 * @author Michell Stuttgart
 */

#ifndef FILEEXCEPTION_H_
#define FILEEXCEPTION_H_

#include "IOException.h"

namespace sgl {
	namespace core {

/**
 * @class FileException
 * @brief Base class responsible for catching exceptions generated by fail in SGL' File loading events.
 *
 * The class handles exceptions caused by events loading of resources such as files.
 *
 */
 class FileException: public IOException {

public:

	 /**
	 * @brief Method responsible for returning a description of the exception.
	 * @return String containing the description of the exception.
	 */
	virtual const char* what() const throw();

};

} /* namespace core */
} /* namespace sgl */

#endif /* FILEEXCEPTION_H_ */
