/**
 * @file IOException.h
 * @date 17/12/2013
 * @author Michell Stuttgart
 */

#ifndef IOEXCEPTION_H_
#define IOEXCEPTION_H_

#include "Exception.h"

namespace sgl {
	namespace core {

/**
 * @class IOException
 * @brief Base class responsible for catching exceptions generated by fail SGL' IO events.
 *
 * Can be used as a basis for other classes that handle exceptions caused by IO events
 * such as loading files.
 *
 */
class IOException: public Exception {

public:

	/**
	 * @brief Method responsible for returning a description of the exception.
	 * @return String containing the description of the exception.
	 */
	virtual const char* what() const throw();

};

} /* namespace core */
} /* namespace sgl */

#endif /* IOEXCEPTION_H_ */
