/**
 * @file ResourceException.h
 * @date 17/12/2013
 * @author Michell Stuttgart
 */

#ifndef RESOURCEEXCEPTION_H_
#define RESOURCEEXCEPTION_H_

#include "IOException.h"

namespace sgl {
	namespace core {

/**
 * @class ResourceException
 * @brief Base class responsible for catching exceptions generated by fail in SGL' loading resource
 * events.
 *
 * The class handles exceptions caused by events loading of resources such as files.
 *
 */
class ResourceException: public IOException {

public:

	/**
	 * @brief Method responsible for returning a description of the exception.
	 * @return String containing the description of the exception.
	 */
	virtual const char* what() const throw();

};

} /* namespace core */
} /* namespace sgl */

#endif /* RESOURCE_EXCEPTION_H_ */
