LUDIC Game Library: Ludic::TMXTileMap::load
checkCollision
drawLayer
getColums
getHeight
getLayer
getRows
getTileHeight
getTileId
getTileWidth
getWidth
hasLayer
load
load
scroll
setPosition
setScreenDimension
setScrollVelocity
setVisible
sizeLayers
TMXTileMap
~TMXTileMap
bool TMXTileMap::load (TMXLoader * loader)
Parameters
loader
Returns
Definition at line 42 of file tmx_tile_map.cpp.
References Ludic::TMXLoader::getColums(), Ludic::TMXLoader::getHeight(), Ludic::TMXLoader::getRows(), Ludic::TMXLoader::getTileHeight(), Ludic::TMXLoader::getTileWidth(), Ludic::TMXLoader::getWidth(), Ludic::TMXLoader::parseLayers(), and Ludic::TMXLoader::parseTileset().