LUDIC Game Library: Ludic::AudioSampleResource::createSampleResource
createSampleResource
operator ALLEGRO_SAMPLE *
~AudioSampleResource
AudioSampleResource * AudioSampleResource::createSampleResource (const String & fileName) static
Parameters
fileName
Returns
Definition at line 21 of file audio_sample_resource.cpp.
References Ludic::ResourceManager::addResource(), Ludic::ResourceManager::getResource(), and Ludic::ResourceManager::Instance().