LUDIC Game Library: Ludic::AnimatedSprite::draw
AnimatedSprite
AnimatedSprite
draw
getHeight
getMask
getWidth
hasAnimation
load
nextFrame
release
setCurrentAnimation
size
~AnimatedSprite
void AnimatedSprite::draw () virtual
Implements Ludic::Layer.
Definition at line 161 of file animated_sprite.cpp.
References Ludic::Sprite::collisionBox, Ludic::Animation::getCurrentFrame(), Ludic::Sprite::getFlip(), Ludic::CollisionBox::getPosition_f(), Ludic::CollisionBox::getPosition_i(), Ludic::Layer::getX(), Ludic::Vector2D::getX(), Ludic::Layer::getY(), Ludic::Vector2D::getY(), and Ludic::Layer::isVisible().