LUDIC Game Library: Ludic::TiledLayer::checkCollision
checkCollision
getHeight
getName
getTile
getWidth
scrool
setPosition
setScreenDimension
setScroolSpeed
size
TiledLayer
bool TiledLayer::checkCollision (const Sprite & spr, int movX, int movY, int tileId)
Parameters
spr
movX
movY
colums
tileId
Returns
Definition at line 183 of file tiled_layer.cpp.
References Ludic::Tile::getBoundingBox(), Ludic::Layer::getHeight(), Ludic::Tile::getId(), getTile(), Ludic::Layer::getWidth(), Ludic::Layer::getX(), and Ludic::Layer::getY().