LUDIC Game Library: main
FPS
main
int main ()
Definition at line 21 of file main_default.cpp.
References Ludic::TiledLayer::checkCollision(), Ludic::Sprite::collidesWithPixel(), Ludic::Font::drawText(), FPS, Ludic::Video::getHeight(), Ludic::TMXTileMap::getLayer(), Ludic::TimeHandler::getTicks(), Ludic::Video::getWidth(), Ludic::KeyboardManager::Instance(), Ludic::Layer::isVisible(), Ludic::KEY_DOWN, Ludic::KEY_ESCAPE, Ludic::KEY_LEFT, Ludic::KEY_M, Ludic::KEY_P, Ludic::KEY_RIGHT, Ludic::KEY_S, Ludic::KEY_SPACE, Ludic::KEY_UP, Ludic::KEY_V, Ludic::KeyboardManager::keyPressed(), Ludic::KeyboardManager::keyRelease(), Ludic::KeyboardManager::keyTyped(), Ludic::AudioSample::load(), Ludic::AudioStream::load(), Ludic::StaticSprite::load(), Ludic::Font::load(), Ludic::TMXTileMap::load(), Ludic::AnimatedSprite::load(), Ludic::Sprite::move(), Ludic::AnimatedSprite::nextFrame(), Ludic::AudioStream::pause(), Ludic::AudioSample::play(), Ludic::AudioStream::play(), Ludic::PLAY_LOOP, Ludic::Video::refresh(), Ludic::Video::setBackgroundColor(), Ludic::Font::setColorFont(), Ludic::Vector2D::setCoordinates(), Ludic::AnimatedSprite::setCurrentAnimation(), Ludic::Video::setIcon(), Ludic::AudioStream::setLoopingMode(), Ludic::Sprite::setPosition(), Ludic::TMXTileMap::setScreenDimension(), Ludic::Font::setText(), Ludic::Video::setTitle(), Ludic::Layer::setVisible(), Ludic::TimeHandler::sleep(), Ludic::TimeHandler::start(), Ludic::AudioStream::stop(), and Ludic::KeyboardManager::update().