LUDIC Game Library: Ludic::Sprite::collidesWithPixel
collidesWithBox
collidesWithPixel
getBoundingBox
getFlip
getMask
move
setFlip
setPosition
bool Sprite::collidesWithPixel (Sprite * s) const virtual
Parameters
s
Returns
Definition at line 37 of file sprite.cpp.
References Ludic::CollisionMask::collisionVerify(), Ludic::Layer::getHeight(), getMask(), Ludic::Layer::getWidth(), Ludic::Layer::getX(), and Ludic::Layer::getY().