LUDIC Game Library: Ludic::StaticSprite::draw
draw
getHeight
getImageResource
getMask
getWidth
load
StaticSprite
StaticSprite
~StaticSprite
void StaticSprite::draw () virtual
Implements Ludic::Layer.
Definition at line 65 of file static_sprite.cpp.
References Ludic::Sprite::getFlip(), getHeight(), getWidth(), Ludic::Layer::getX(), Ludic::Layer::getY(), and Ludic::Layer::isVisible().