LUDIC Game Library: Ludic::StaticSprite::load
draw
getHeight
getImageResource
getMask
getWidth
load
StaticSprite
StaticSprite
~StaticSprite
bool StaticSprite::load (const String & fileName)
Parameters
fileName
Returns
Definition at line 24 of file static_sprite.cpp.
References Ludic::Sprite::collisionBox, getHeight(), getWidth(), Ludic::Layer::getX(), Ludic::Layer::getY(), Ludic::CollisionMask::initMask(), Ludic::ImageResource::loadImageResource(), Ludic::CollisionBox::setDimension(), Ludic::CollisionBox::setPosition(), and Ludic::Exception::what().