LUDIC Game Library: Ludic::AudioStreamResource::createAudioStreamResource
createAudioStreamResource
getBuff
getSamples
operator ALLEGRO_AUDIO_STREAM *
~AudioStreamResource
AudioStreamResource * AudioStreamResource::createAudioStreamResource (const String & fileName, unsigned int buff, unsigned int samples) static
Parameters
fileName
buff
samples
Returns
Definition at line 22 of file audio_stream_resource.cpp.
References Ludic::ResourceManager::addResource(), Ludic::ResourceManager::getResource(), and Ludic::ResourceManager::Instance().